services:
  hypergo-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: hypergo-server
    ports:
      - "80:8079"
    volumes:
      - ./server/shortcuts.json:/app/shortcuts.json
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "https://go.geethg.com/admin"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - hypergo_network

  hypergo-frontend:
    build: ./client
    container_name: hypergo-frontend
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - ./client:/app
    command: ["pnpm", "run", "start"]
    depends_on:
      - hypergo-server
    networks:
      - hypergo_network

networks:
  hypergo_network:
    driver: bridge
