services:
  hypergo-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: hypergo-server
    ports:
      - "80:8079"
    volumes:
      - ./server/shortcuts.json:/app/shortcuts.json
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "https://go.geethg.com/admin"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - hypergo_network

  hypergo-frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: hypergo-frontend
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - hypergo_network
    depends_on:
      - hypergo-server

networks:
  hypergo_network:
    driver: bridge