{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}-redis
  labels:
    app: {{ .Values.global.name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          
          {{- if .Values.redis.persistence.enabled }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
          {{- end }}

      {{- if .Values.redis.persistence.enabled }}
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ .Values.global.name }}-redis-data
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}-redis
spec:
  selector:
    app: {{ .Values.global.name }}-redis
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
---
{{- if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.name }}-redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}
{{- end }}


